global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['node-app:3000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']    
